all:
	wget https://raw.githubusercontent.com/irssi/scripts.irssi.org/master/scripts/uberprompt.pl -O uberprompt.pl
	wget https://raw.githubusercontent.com/irssi/scripts.irssi.org/master/scripts/ido_switcher.pl -O ido_switcher.pl
	wget https://raw.githubusercontent.com/irssi/scripts.irssi.org/master/scripts/history_search.pl -O history_search.pl
	wget https://raw.githubusercontent.com/irssi/scripts.irssi.org/master/scripts/colon_emoji.pl -O colon_emoji.pl
	wget http://anti.teamidiot.de/static/nei/*/Code/Irssi/emoji_def.txt -O emoji_def.txt
